name: wfrp-companion
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pymupdf
  - poppler
  - tesseract
  - fastapi
  - uvicorn
  - pillow
  - opencv
  - imagehash
  - openai
  - pytorch
  - sentence-transformers
  - pytest
  - pytest-cov
  - ruff
